### ISSUE TITLE
hi, encode error, ex. "0"

### ISSUE THREAD

**Issue by wolance** [zhicheng/base64#11]
online base64 encode   0 -> MA==
but  yours  0 -> MAA=
if "MAA=" decode online....  then     
![图片](https://user-images.githubusercontent.com/55013484/68636167-9a65f480-0535-11ea-8245-395abd01ede4.png)
not good i feel.

**Comment by zhicheng** [comment]
Can you post your code?

here is my test
```
$ cat main2.c
#include <stdio.h>
#include <string.h>
#include "base64.h"

int
main(void)
{
        char buf[4];
        unsigned char buf2[4];
        base64_encode((unsigned char *)"0", 1, buf);
        printf("%s\n", buf);

        base64_decode(buf, strlen(buf), buf2);
        printf("%s\n", buf2);

        return 0;
}
$ cc main2.c base64.c
$ ./a.out
MA==
0
```

**Comment by wolance** [comment]
well . I know why, yes I guess. ‘\0’ end the string and part in calculation.
