### ISSUE TITLE
data structure about base64

### ISSUE THREAD

**Issue by terrantsh** [zhicheng/base64#5]
Hello! If i want to encrypt some data about Hex. May I use Hex format encrypt with base64? And could I get decrypted data in Hex format. Thank you!

**Comment by zhicheng** [comment]
Not quit sure what you want do, If you mean Hex is 0x1234,it's just an int, you need encode it into byte array like char *(because endianness issue). if you mean raw byte array just represent in Hex. It's ok to use base64 encode and decode.

**Comment by terrantsh** [comment]
Thank you so much. I have worked out my problem. My data just like {0x12,0x23,0x32}. I used a stupid method. I Change my format to str like 122332. Then use base64 to encode. And after decode use Str2Hex function to get my data.

**Comment by zhicheng** [comment]
if you are talking about hex string like "1234abcd", I might have another project can doing this, encode raw string to hex string and decode hex string to raw string. 

check out https://github.com/zhicheng/binascii
