### ISSUE TITLE
utf-8 support?

### ISSUE THREAD

**Issue by r3verser** [zhicheng/base64#6]
Hi, i have tried this with utf8 string in russian "АБГДЕ", but got error
```
Expression: memcmp(encode_out, decode, decodelen) == 0
This application has requested the Runtime to terminate it in an unusual way.
```
Should it work with it, or any workaround/ideas? Thanks.

**Comment by zhicheng** [comment]
Can you post you demo code? I tested you string, no error.
By the way, main.c is for testing, you should have you raw string and base64 string set right.
for example test string "АБГДЕ":

`
test((void *)"АБГДЕ", strlen("АБГДЕ"), "0JDQkdCT0JTQlQ==", strlen("0JDQkdCT0JTQlQ=="));
`

Base64 is binary encoding, should have any problem with UTF-8 or any other encoding.

**Comment by r3verser** [comment]
Thanks, it was my inattention, all works as it should! :+1:
