### ISSUE TITLE
macro BASE64_DECODE_OUT_SIZE(s) maybe needs plus 1

### ISSUE THREAD

**Issue by ZRiemann** [zhicheng/base64#8]
#define BASE64_DECODE_OUT_SIZE(s) ((unsigned int)(((s) / 4) * 3))

dec = malloc(BASE64_DECODE_OUT_SIZE(32));
base_decode(enc, enc_len, dec);

according to base64.c line 160;
out[j] = '\0'; // if not plus 1, out[j] is out of bound

maybe define the macro as follow: 
#define BASE64_DECODE_OUT_SIZE(s) ((unsigned int)(((s) / 4) * 3 + 1))

**Comment by zhicheng** [comment]
you're right, but I think `out[j] = '\0'` should be removed, base64 can encode a string within '\0', so it's pointless add a '\0' at the end. I'll update or you can send me a pull requests.
